# 提权操作
ansible_become: true

# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_ssh_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"
# apiserver ip
KUBE_APISERVER_IP: >-
  {% if lb_kube_apiserver_ip is not defined %}
    127.0.0.1
  {% else %}
    {{ lb_kube_apiserver_ip }}
  {% endif %}

CLUSTER_DNS_SERVICE_IP: "{{ kube_service_subnet | ipaddr('net') | ipaddr(10) | ipaddr('address') }}"

# Pod根容器
pod_infra_container_image: "{{ local_hostname }}:{{ registry_port }}/kubeoperator/pause:3.2"
# coredns镜像
coredns_image: "{{ local_hostname }}:{{ registry_port }}/kubeoperator/coredns:1.6.7"