- name: 下载解压 kubeadm kubelet kubectl 二进制文件和 apiserver controller-manager kube-scheduler 镜像文件
  unarchive:
    src: "http://{{local_hostname}}:{{repo_port}}/repository/raw/k8s/k8s.tar.gz"
    dest: "{{ base_dir }}/"
    mode: "0755"
    copy: no

- name: 拷贝 kubeadm kubelet kubectl 二进制文件
  copy:
    src: "{{ base_dir}}/k8s/k8s-tools/{{ item }}"
    dest: "{{ bin_dir }}/"
    remote_src: yes
    mode: "0755"
  with_items:
  - kubeadm
  - kubelet
  - kubectl

- name: 下载解压基础 cni plugins
  unarchive:
    src: "http://{{local_hostname}}:{{repo_port}}/repository/raw/k8s/cni.tar.gz"
    dest: "{{ base_dir }}/"
    mode: "0755"
    copy: no

- name: 拷贝 cni plugins 二进制文件
  copy:
    src: "{{ base_dir}}/cni/{{ item }}"
    dest: "{{ bin_dir }}/"
    remote_src: yes
    mode: "0755"
  with_items:
  - bridge
  - host-local
  - loopback
  - portmap

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
    - /etc/kubernetes/images
    - /etc/kubernetes/manifests
    - /usr/lib/systemd/system/kubelet.service.d

- name: 创建kubelet的systemd unit文件
  template: src=kubelet.service.j2 dest=/usr/lib/systemd/system/kubelet.service

- name: 创建kubelet的配置文件
  template: src=10-kubeadm.conf.j2 dest=/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: 创建kubelet的参数文件
  template: src=kubelet.config.j2 dest=/etc/sysconfig/kubelet

- name: 开机启用kubelet 服务
  shell: systemctl enable kubelet
  ignore_errors: true

- name: 配置 kubectl 命令自动补全
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'kubectl completion'
    line: 'source <(kubectl completion bash)'

- block:
  - name: 拷贝 kube-master 镜像文件
    copy:
      src: "{{ base_dir}}/k8s/{{ item }}"
      dest: "/etc/kubernetes/images/{{ item }}"
      remote_src: yes
      mode: "0755"
    with_items:
    - kube-apiserver.tar
    - kube-controller-manager.tar
    - kube-scheduler.tar

  - name: 加载 kube-master 镜像
    shell: "{{ bin_dir }}/docker load -i /etc/kubernetes/images/{{ item }}"
    with_items:
    - kube-apiserver.tar
    - kube-controller-manager.tar
    - kube-scheduler.tar
    when: container_runtime == 'docker'

  - name: 加载 kube-master 镜像
    shell: "{{ bin_dir }}/ctr -n=k8s.io images import /etc/kubernetes/images/{{ item }}"
    with_items:
    - kube-apiserver.tar
    - kube-controller-manager.tar
    - kube-scheduler.tar
    when: container_runtime == 'containerd'
  when: inventory_hostname in groups['kube-master']

- block:
  - name: 拷贝 kube-proxy 镜像文件
    copy:
      src: "{{ base_dir}}/k8s/{{ item }}"
      dest: "/etc/kubernetes/images/{{ item }}"
      remote_src: yes
      mode: "0755"
    with_items:
    - kube-proxy.tar

  - block:
    - name: 加载 kube-proxy 镜像
      shell: "{{ bin_dir }}/docker load -i /etc/kubernetes/images/{{ item }}"
      with_items:
      - kube-proxy.tar

    - name: Docker | 下载 pause 镜像
      shell: "{{ bin_dir }}/docker pull {{ pod_infra_container_image }}"

    - name: Docker | 下载 coredns 镜像
      shell: "{{ bin_dir }}/docker pull {{ coredns_image }}"
    when: container_runtime == 'docker'

  - block:
    - name: 加载 kube-proxy 镜像
      shell: "{{ bin_dir }}/ctr -n=k8s.io images import /etc/kubernetes/images/{{ item }}"
      with_items:
      - kube-proxy.tar

    - name: Containerd | 下载 pause 镜像
      shell: "{{ bin_dir }}/ctr -n=k8s.io images pull {{ pod_infra_container_image }}"

    - name: Containerd | 下载 coredns 镜像
      shell: "{{ bin_dir }}/ctr -n=k8s.io images pull {{ coredns_image }}"
    when: container_runtime == 'containerd'
  when: inventory_hostname in (groups['kube-worker'] + groups['new-worker'])