- hosts: all
  roles:
  - prepare/repository
  - prepare/base
  - chrony
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - prepare/kubernetes
  - prepare/etcd-certificates
  - prepare/kube-certificates

- hosts: all
  roles:
  - role: load-balancer

- hosts: 
  - etcd
  - kube-master
  roles:
  - etcd

- hosts: kube-master
  roles:
  - kube-master

- hosts: 
  - kube-worker
  - new-worker
  roles:
  - kube-worker

- hosts: 
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - post

- hosts: all
  roles:
  - role: plugins/network-plugins

- hosts: kube-master[0]
  roles:
  - plugins/metrics-server
  - plugins/npd
  - helm
  - plugins/ingress-controller
