- hosts: all
  # max_fail_percentage: 99
  roles:
  - prepare/repository
  - prepare/base
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - prepare/kubernetes
  - prepare/certificates

- hosts: all
  roles:
  - role: load-balancer

- hosts: 
  - etcd
  - kube-master
  roles:
  - etcd

- hosts: 
  - kube-master
  - kube-worker
  - new-worker
  # roles:
  # - kube-certificates

- hosts: kube-master
  roles:
  - kube-master

- hosts: 
  - kube-worker
  - new-worker
  roles:
  - kube-worker

- hosts: 
  - kube-master
  - kube-worker
  - new-worker
  roles:
  - post

- hosts: kube-master[0]
  roles:
  - plugins/network-plugins
  - plugins/cluster-storage
  # - plugins/cert-manager
  # - plugins/ingress-controller
  # - plugins/metrics-server
  # - plugins/kubernetes-dashboard
