- hosts: all
  vars_prompt:
    name: "restore_confirmation"
    prompt: "确实要恢复群集吗? 输入“yes”确认恢复群集。"
    default: "no"
    private: no
  pre_tasks:
    - name: 恢复确认
      fail:
        msg: "恢复确认失败，取消恢复集群操作。"
      when: restore_confirmation != "yes"
  roles:
  - prepare/base
  - { role: prepare/docker, when: "container_runtime == 'docker'" }
  - { role: prepare/containerd, when: "container_runtime == 'containerd'" }
  - prepare/kubernetes
  - restore