- name: 获取所有已经创建的 storageclass 信息
  command: "kubectl get storageclass"
  register: sc_info
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- import_tasks: vsphere.yml
  when: '"vsphere" in sc_info.stdout'