- block:
  - name: 下载解压 govc 二进制文件
    get_url:
      url: "{{ govc_download_url }}"
      dest: "{{ base_dir }}/"
      timeout: "{{ download_timeout_online }}"

  - name: 解压 govc 二进制文件
    shell: "gunzip {{ base_dir }}/govc_linux_{{ architectures }}.gz"

  - name: 拷贝 govc 二进制文件
    copy:
      src: "{{ base_dir}}/govc_linux_{{ architectures }}"
      dest: "{{ bin_dir }}/govc"
      remote_src: yes
      mode: "0755"

  - name: 移除 govc 二进制文件
    file:
      name: "{{ base_dir }}/govc_linux_{{ architectures }}"
      state: absent

  - name: 创建 cloud-config 目录
    file:
      name: "{{ cloud_config_dir }}"
      state: directory

  - name: prepare setup.sh
    template:
      src: vsphere/setup.sh.j2
      dest: "{{ cloud_config_dir }}/setup.sh"

  - name: install jq
    yum:
      name:
      - jq

  - name: set disk.enableuuid to true for all vms
    shell: "bash setup.sh"
    args:
      chdir: "{{ cloud_config_dir }}"
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: modify kubelet cloud provider params on worker
  lineinfile:
    dest: /etc/sysconfig/kubelet
    regexp: '^KUBELET_EXTRA_ARGS'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --cloud-provider=vsphere'

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: restart docker
  service:
    name: docker
    state: restarted
  delegate_to: "{{ item }}"
  with_items:
  - "{{ groups['kube-master'] }}"
  - "{{ groups['kube-worker'] }}"
  - "{{ groups['new-worker'] }}"

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['kube-master'] }}"
    - "{{ groups['kube-worker'] }}"
    - "{{ groups['new-worker'] }}"