# 提权操作
ansible_become: true
# 判断系统架构，arm64 或 amd64
architectures: "{% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'aarch64' %}arm64{% endif %}"
# ----------------------- k8s二进制文件下载地址 ------------------
k8s_download_url: "http://{{ local_hostname }}:{{ repo_port }}/repository/raw/k8s/version/{{ kube_version }}/{{ architectures }}/k8s.tar.gz"
