- name: "禁止 worker 节点：{{ inventory_hostname }} 进行调度"
  shell: kubectl cordon {{ inventory_hostname }}
  ignore_errors: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: "驱逐 worker 节点：{{ inventory_hostname }} 上运行的 Pod"
  shell: >
    kubectl drain
    --force
    --ignore-daemonsets
    --grace-period {{ drain_grace_period }}
    --timeout {{ drain_timeout }}
    --delete-local-data {{ inventory_hostname }}
  ignore_errors: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 取消节点原有 worker 角色标签
  shell: >
    kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker='' --overwrite &&
    kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker-
  ignore_errors: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: "移除节点：{{ inventory_hostname }}"
  shell: kubectl delete node {{ inventory_hostname }}
  ignore_errors: true
  delegate_to: "{{ groups['kube-master'][0] }}"