- name: 创建 etcd 备份目录
  file:
    name: /etc/kubernetes/backup/etcd
    state: directory

- name: 备份 etcd 数据库
  shell: "cd /etc/kubernetes/backup/etcd && \
      ETCDCTL_API=3 {{ bin_dir }}/etcdctl snapshot save etcd-snapshot.db"

- name: 压缩备份文件
  archive:
    path: "/etc/kubernetes/backup/etcd/etcd-snapshot.db"
    dest: "/etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz"
    format: gz
    force_archive: true

- name: 拉取备份至本地
  fetch:
    src: /etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz
    dest: "{{ (playbook_dir + '/cluster-backup/' + 'etcd-snapshot.tar.gz') }}"
    flat: yes

- name: 移除 etcd 临时备份文件
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "/etc/kubernetes/backup/etcd/etcd-snapshot.db"
    - "/etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz"