- name: Create etcd backup directory
  file:
    name: /etc/kubernetes/backup/etcd
    state: directory

- name: Backup etcd database
  shell: "cd /etc/kubernetes/backup/etcd && \
      ETCDCTL_API=3 {{ bin_dir }}/etcdctl snapshot save etcd-snapshot.db"

- name: Archive backup file
  archive:
    path: "/etc/kubernetes/backup/etcd/etcd-snapshot.db"
    dest: "/etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz"
    format: gz
    force_archive: true

- name: Fetch backup file
  fetch:
    src: /etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz
    dest: "{{ ('/backup/' + cluster_name + '/etcd-snapshot.tar.gz') }}"
    flat: yes

- name: Remove etcd temp backup file
  file:
    name: "{{ item }}"
    state: absent
  with_items:
  - "/etc/kubernetes/backup/etcd/etcd-snapshot.db"
  - "/etc/kubernetes/backup/etcd/etcd-snapshot.tar.gz"