- name: 安装 haproxy
  package: name=haproxy state=present

- name: 创建 haproxy 配置目录
  file: name=/etc/haproxy state=directory

- name: 修改 haproxy.service
  template:
    src: haproxy/haproxy.service.j2
    dest: /usr/lib/systemd/system/haproxy.service

- name: 配置 haproxy
  template:
    src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: daemon-reload for haproxy.service
  shell: systemctl daemon-reload

- name: 开机启用haproxy服务
  service:
    name: haproxy
    enabled: yes

- name: 开启haproxy服务
  service:
    name: haproxy
    state: started