- name: Create repository backup directory
  file:
    path: /etc/yum.repos.d/bak
    state: directory

- name: Backup the old repository
  shell: "mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak >/dev/null 2>&1  || ls /etc/yum.repos.d/ >/dev/null 2>&1"

- name: Remove other repository
  file:
    path: /etc/yum.repos.d/*
    state: absent

- block:
  - name: Add offline repository
    template:
      src: kubeops.repo.amd64.j2
      dest: /etc/yum.repos.d/kubeops.repo
    when: architectures == 'amd64'

  - name: Add offline repository
    template:
      src: kubeops.repo.arm64.j2
      dest: /etc/yum.repos.d/kubeops.repo
    when: architectures == 'arm64'
  when: ansible_distribution in [ 'CentOS','RedHat' ]

- block:
    - name: Add offline repository
      template:
        src: kubeops.repo.amd64-euler.j2
        dest: /etc/yum.repos.d/kubeops.repo
      when: architectures == 'amd64'

    - name: Add offline repository
      template:
        src: kubeops.repo.arm64-euler.j2
        dest: /etc/yum.repos.d/kubeops.repo
      when: architectures == 'arm64'
  when: ansible_distribution in [ 'EulerOS' ]

- block:
    - name: Test ping www.badiu.com
      shell: ping -c 4 www.baidu.com
      register: ping

    - name: Add aliyun repository
      get_url: 
        url: http://mirrors.aliyun.com/repo/Centos-7.repo
        dest: /etc/yum.repos.d/CentOS-Base.repo 
      when: architectures == 'amd64'

    - name: Add aliyun repository
      get_url: 
        url: http://mirrors.aliyun.com/repo/Centos-altarch-7.repo
        dest: /etc/yum.repos.d/CentOS-altarch.repo 
      when: architectures == 'arm64'
  when: ansible_distribution in [ 'CentOS','RedHat' ] and '"ttl" in ping'
