- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "/var/lib/etcd"    # etcd 工作目录

- name: 下载解压 etcd 二进制文件
  unarchive:
    src: "{{ etcd_download_url }}"
    dest: "{{ base_dir }}/"
    mode: "0755"
    copy: no

- name: 拷贝 etcd 二进制文件
  copy:
    src: "{{ base_dir}}/etcd/{{ item }}"
    dest: "{{ bin_dir }}/"
    remote_src: yes
    mode: "0755"
  with_items:
  - etcd
  - etcdctl

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
